apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
#  This one below technically is useless:
#  values:
#    global:
#      k8sIngress:
#        enabled: false
